
# Raw gift data without image URLs
raw_gifts = [
    {"name": "Termichy Stackable Formula Dispenser Portable Milk Powder Container, 2 Pack, Grey", "link": "https://www.amazon.com/dp/B09V277ZRJ", "reserved_by": None},
    {"name": "Baby Jolie Memory for Babies, Alcohol Free Cologne", "link": "https://www.amazon.com/dp/B07HHJ3K5W", "reserved_by": None},
    {"name": "Baby Jolie Le Bebe Kids Perfume with Flower and Fruits Scent", "link": "https://www.amazon.com/dp/B00RIC9EUK", "reserved_by": None},
    {"name": "XMWEALTHY Newborn Baby Wrap Swaddle Blanket Knit Sleeping Bag", "link": "https://www.amazon.com/dp/B01N2NADKZ", "reserved_by": None},
    {"name": "Aablexema Baby Cotton Fooltess Pajamas with Mitten, 3-packt", "link": "https://www.amazon.com/dp/B0CSNJGY8R", "reserved_by": None},
    {"name": "Simple Joys by Carter's Baby 3-Pack Neutral Sleep and Play", "link": "https://www.amazon.com/dp/B075YZ1963", "reserved_by": None},
    {"name": "Mustela Newborn Arrival Gift Set - Baby Skincare & Bath Time Essentials", "link": "https://www.amazon.com/dp/B01NA7ZMIA", "reserved_by": None},
    {"name": "Aquaphor Baby Skincare Essentials Gift Set with Baby Wash and Shampoo", "link": "https://www.amazon.com/dp/B0CLHDBYR9", "reserved_by": None},
    {"name": "Baby Wet Wipes Dispenser and Diaper Wipe Warmer with Night Light,Temperature", "link": "https://www.amazon.com/dp/B08JYJKZNL", "reserved_by": None},
    {"name": "Dr. Brown's Natural Flow Anti-Colic Options+ Narrow Glass Baby Bottle 4", "link": "https://www.amazon.com/dp/B0F54RF5BZ", "reserved_by": None},
    {"name": "WaterWipes Plastic-Free Original Baby Wipes, 99.9% Water Based Wipes", "link": "https://www.amazon.com/dp/B008KJEYLO", "reserved_by": None},
    {"name": "Lictin Baby Hair Brush and Comb Set, 4 Pcs Newborn Hair Brush with Soft Bristle", "link": "https://www.amazon.com/dp/B0D12Q1FH9", "reserved_by": None},
    {"name": "5-Pack Muslin Burp Cloths Baby Boy, Girl - Very Absorbent Baby Burp Cloth Rags", "link": "https://www.amazon.com/dp/B0CC99GX75", "reserved_by": None},
    {"name": "rida Baby Control The Flow Bathtub Sprayer Attachment for Baby Bathtub", "link": "https://www.amazon.com/dp/B0DXXH3S2P", "reserved_by": None},
    {"name": "Diaper Bag Backpack Baby Diaper Bag Leather with 17 Diaper Bag Organizing Pouches", "link": "https://www.amazon.com/dp/B0BLBM99XG", "reserved_by": None},
    {"name": "GROWNSY Nasal Aspirator for Baby, Electric Baby Nose Sucker", "link": "https://www.amazon.com/dp/B08CMWHD3B", "reserved_by": None},
    {"name": "Momcozy Baby Carrier - Ergonomic, Cozy and Lightweight Carrier for 7-44lbs", "link": "https://www.amazon.com/dp/B0CDQ1ZLJ9", "reserved_by": None},
    {"name": "THERMOS Stainless King Vacuum-Insulated Beverage Bottle, 40 Ounce, Matte Stainless Steel", "link": "https://www.amazon.com/dp/B01DZQT3IU", "reserved_by": None},
    {"name": "Baby Sensory Toy 0-6 Month Music Animal Stuffed Plush Caterpillar Toy for Infant 0-3-6 Month", "link": "https://www.amazon.com/dp/B0CDWW374H", "reserved_by": None},
    {"name": "Smart Video Baby Monitor with Camera and Audio,Dual Mode,WiFi On/Off t", "link": "https://www.amazon.com/dp/B0CZHFQNYY", "reserved_by": None},
    {"name": "Baby Walker with Wheels, 5 in 1 Baby Walkers for Boys Girls 6-12 Months", "link": "https://www.amazon.com/dp/B0DS19ZLNZ", "reserved_by": None},
    {"name": "Lilian&Gema Baby Healthcare and Grooming Kit, 28-in-1 Rechargeable Nail Trimmer Electric Set", "link": "https://www.amazon.com/dp/B0DPCJ2R24", "reserved_by": None},
    {"name": "4 Pcs Fleece 30 x 40 Fluffy Baby Blanket for Boys Nursery Little Girl Infant or Newborn", "link": "https://www.amazon.com/dp/B0CY2Q2C4P", "reserved_by": None},
    {"name": "SWEET DOLPHIN Baby Sleep Sack 0-6 Months", "link": "https://www.amazon.com/dp/B0DPKWG3PN", "reserved_by": None},
    {"name": "Nursing Pillow and Positioner, Breastfeeding, Bottle Feeding", "link": "https://www.amazon.com/dp/B09H6XX51K", "reserved_by": None},
    {"name": "NutriBullet NBY-50100 Baby Complete Food-Making System, 32-Oz, White, Blue, Clear", "link": "https://www.amazon.com/dp/B086DFCS7Y", "reserved_by": None},
    {"name": "nutribullet Baby BSR-0801N Turbo Food Steamer", "link": "https://www.amazon.com/dp/B006SODTTQ", "reserved_by": None},
    {"name": "No-Touch Forehead Thermometer for Adults and Kids, Fast Accurate Baby Thermometer", "link": "https://www.amazon.com/dp/B0CKW3K16P", "reserved_by": None},
    {"name": "Bottle Sterilizer and Dryer, HIYAKOI Electric Steam Baby Bottle Sterilizer and Dryer", "link": "https://www.amazon.com/dp/B0D474DSB6", "reserved_by": None},
    {"name": "Paruu Hands Free Breast Pump P16, Wearable Breast Pump Electirc Portable with 4 Modes & 12 Levels", "link": "https://www.amazon.com/dp/B0DLB6H6NM", "reserved_by": None},
    {"name": "Philips Avent Natural Newborn Glass Gift Set, Baby Bottles with Natural Response Nipples", "link": "https://www.amazon.com/dp/B098Z6HYGV", "reserved_by": None},
    {"name": "Tommee Tippee Advanced Anti-Colic Ready for Baby BPA Free 14 Piece Set, 5oz & 9oz Bottles", "link": "https://www.amazon.com/dp/B0CQMF9SGQ", "reserved_by": None},
    {"name": "Reginary 4 Pack Baby Hooded Towels Coral Fleece Baby Bath Towels 30 x 30 Inch Soft Absorbent Hooded Bath", "link": "https://www.amazon.com/dp/B0BFHRFXMD", "reserved_by": None},
    {"name": "UKIN Baby Washcloths - Soft Face Cloths for Newborn, Absorbent Bath Face Towels", "link": "https://www.amazon.com/dp/B0B1V5NNXD", "reserved_by": None},
    {"name": "3 Tier Rolling Cart - Baby Diaper Caddy Organizer", "link": "https://www.amazon.com/dp/B0D2VW6DW6", "reserved_by": None},
    {"name": "Montessori Baby Toy for 1+ Year Old Sorting Stacking Learning Toys 6 to 12 Months", "link": "https://www.amazon.com/dp/B0CBV56MRK", "reserved_by": None},
    {"name": "iaper Genie Select Pail (Grey) is Made of Durable Stainless", "link": "https://www.amazon.com/dp/B0CNS4H334", "reserved_by": None},
    {"name": "Kinder King Baby High Chair, 8 in 1 Coverts to Dining Booster", "link": "https://www.amazon.com/dp/B0D5QSWZ91", "reserved_by": None},
    {"name": "Baby Bathtub, Collapsible Newborn Bathtub for Infant to Toddler 0-24 Months", "link": "https://www.amazon.com/dp/B0CTJXJL4T", "reserved_by": None},
    {"name": "Dancing Talking Cactus Toy for Baby Toddler, Boys Girls Gifts Singing Mimicking", "link": "https://www.amazon.com/dp/B0C1SJVKCH", "reserved_by": None},
    {"name": "Baby Einstein 4-in-1 Kickin' Tunes Music and Language Play Gym and Piano", "link": "https://www.amazon.com/dp/B07MPCCDM7", "reserved_by": None}
]
